### ISSUE TITLE
Plugin should be tied to "validate", not "verify"

### ISSUE THREAD

**Issue by nguillaumin** [ec4j/editorconfig-maven-plugin#25]
Hi,

I believe the "validate" phase of Maven would be more appropriate to tie the plugin to, rather than "verify". "verify" is to check the integrity of the generated artifact (i.e. JAR file) at the end of the build, whereas "validate" is to validate the project before the build starts.

Thanks!

**Comment by ppalaga** [comment]
Hi @nguillaumin, using `verify` by default is a result of a thorough discussion at one of my former teams. My colleagues strongly prefered performing these checks after running the tests. The present default is thus intentional and I do not  incline to change it at this time.

If you do not like the default, you can change the phase easily in the `pom.xml` of our project.

**Comment by nguillaumin** [comment]
Ok, fair enough. What tripped me up is that I usually use `package` as my default goal, so `verify` is never called until I call it explicitly...
