### ISSUE TITLE
Plugin not apply  indent_style, indent_size to *.java files

### ISSUE THREAD

**Issue by jorgetovaradl** [ec4j/editorconfig-maven-plugin#38]
I need to format the ***.java** code with indent_style, indent_size configured in the .editorconfig but I don't see any changes when executing the phase `mvn editorconfig:format`.

My plugin in the pom.xml is this 
```
			<plugin>
				<groupId>org.ec4j.maven</groupId>
				<artifactId>editorconfig-maven-plugin</artifactId>
				<version>0.0.10</version>
				<executions>
					<execution>
						<id>check</id>
						<phase>verify</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<includes>
						<include>**/*.java</include>
					</includes>
				</configuration>
			</plugin>
```

**Comment by ppalaga** [comment]
Java files won't get indented, because there is currently no Linter for those - see https://github.com/ec4j/editorconfig-maven-plugin#how-it-works 
Indenting structured languages is not possible without parsing the files. I work on a Java Linter based on Eclipse JDT formatter in https://github.com/ec4j/editorconfig-java-domain and it will take a while till it is ready for the end users.

Closing because the reported behavior is expected at this time.
